D_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import (login_view, register_view, logout_view)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include('posts.urls', namespace='posts')),
    url(r'^api/users/', include('accounts.api.urls', namespace='users-api')),
    url(r'^api/posts/', include('posts.api.urls', namespace='posts-api')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url
from .views import (PostListAPIView, PostDetailAPIView,
                    PostUpdateAPIView, PostDeleteAPIView,
                    PostCreateAPIView)


urlpatterns = [
    url(r'^$', PostListAPIView.as_view() ,name='list'),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', PostDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),
]

posts/urls.py
from django.conf.urls import url
from .views import (post_list,
                    post_create,
                    post_update,
                    post_detail,
                    post_delete,
                    )



urlpatterns = [
    url(r'^$', post_list ,name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<pk>\d+)/edit/$', post_update, name='update'),
    url(r'^(?P<pk>\d+)/$', post_detail, name='detail'),
    url(r'^(?P<pk>\d+)/delete/$', post_delete),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils import timezone
from markdown_deux import markdown
#to specify image upload location we define a function

#def upload_location(instance, filename):
   # return "%s/%s" % (instance.pk, filename)

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    image = models.ImageField(null=True,
                              blank=True,)
                              #upload_to=upload_location)

    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})


    # for latest posts on top of page
    class Meta:
        ordering = ['-timestamp', 'updated']

    def get_markdown(self):
        content = self.content
        return markdown(content)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

posts/api/views.py
from rest_framework.generics import (
                                    ListAPIView, RetrieveAPIView,
                                    UpdateAPIView,DestroyAPIView,
                                    CreateAPIView,
                                    RetrieveUpdateAPIView, #to auto fill before editing
                                    )

from posts.models import Post
from .serializers import (
    PostListSerializer,
    PostDetailSerializer,
    PostCreateSerializer)

from rest_framework.permissions import (AllowAny,IsAdminUser,
                                        IsAuthenticated,
                                        IsAuthenticatedOrReadOnly)

from .permissions import IsOwnerOrReadOnly

from rest_framework.filters import (SearchFilter,OrderingFilter)

#from rest_framework.pagination import (LimitOffsetPagination,PageNumberPagination)

from .pagination import (PostLimitOffsetPagination,
                         PostPageNumberPagination)

class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer
    permission_classes = [IsAuthenticated]

    #to know the user who created the post
    def perform_create(self, serializer):
        serializer.save(user = self.request.user)

class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer

    # for filtering queryset:
    filter_backends = [SearchFilter,OrderingFilter]
    search_fields = ['title', 'user__first_name', 'content']

    '''
    note: for filtering with both search and order filter use '&'
    symbol between '?search' and 'ordering' in url
    '''
    pagination_class = PostPageNumberPagination



class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwnerOrReadOnly]

    # to know the user who updated the post
    def perform_update(self, serializer):
        serializer.save(user= self.request.user)

class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwnerOrReadOnly]

posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
# from django.core.urlresolvers import reverse

from .models import Post
from .forms import PostForm


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
        # or
        # url = reverse('detail', kwargs={'create': post_create})
        # return HttpResponseRedirect(url)

    context = {
        'form': form
    }
    return render(request, 'posts_form.html', context)


def post_detail(request, pk=None):
    instance = get_object_or_404(Post, pk=pk)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    context = {
        'title': instance.title,
        'instance': instance,
        'share_string': share_string,
    }
    return render(request, 'posts_detail.html', context)


def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()
    if not request.user.is_staff or not request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
                        Q(title__icontains=query)|
                        Q(content__icontains =query)|
                        Q(user__first_name__contains=query)|
                        Q(user__last_name__contains=query)
                        )
    paginator = Paginator(queryset_list, 10)  # Show 25 contacts per page

    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        'objects_list': queryset,
        'title': 'List',
        'page_request_var': page_request_var,
        'today': today,
    }

    return render(request, 'posts_list.html', context)


def post_update(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully Updated")
        return HttpResponseRedirect(instance.get_absolute_url())
        # or
        # url = reverse('detail', kwargs={'pk': pk})
        # return HttpResponseRedirect(url)
    context = {
        'title': instance.title,
        'instance': instance,
        'form': form,
    }
    return render(request, 'posts_form.html', context)


def post_delete(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, pk=pk)
    instance.delete()
    messages.success(request, "Successfully Deleted")
    return redirect("posts : list")

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            D_Blog
        {% endblock title %}
    </title>

<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'posts:list' %}">Home</a></li>

        {% block post_detail_link %}
        
        {% endblock %}
    
        {% if not request.user.is_authenticated %}
        <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
        <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
        {% else %}
            <li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
        {% endif %}


    </ol>


</div>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" \
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" \
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% block head_extra %}


{% endblock head_extra %}
</head>
    <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    {% include 'messages_display.html' %}
    <div class="container">
        {% block content %}


        {% endblock content %}
    </div>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" \
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.content-markdown').each(function () {
                var content = $(this).text();
                var markedContent = marked(content);
                $(this).html(markedContent)
            });
            $('.post-detail-item img').each(function () {
                $(this).addClass('img-responsive')
            });
            var titleInput = $('#id_title');

            
            function setTitle(value) {
                $('#preview-title').text(value);
            }
            setTitle(titleInput.val());

            titleInput.keyup(function () {
                var newTitle = $(this).val();
                setTitle(newTitle)

            });

            var contentInput = $('#id_content');


            function setContent(value) {
                var markedContent = marked(value);
                $('#preview-content').html(markedContent);
                $('#preview-content img').each(function () {
                    $(this).addClass('img-responsive')

                })

            }
            setContent(contentInput.val())

            contentInput.keyup(function () {
                var newContent = $(this).val();
                setContent(newContent)
            })


        })
    </script>

    </body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="col-sm-6 col-sm-offset-3">
        <h1>{{ title }}</h1>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-default" value="{{ title }}">
        </form>
    </div>
{% endblock content %}

templates/messages_display.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/posts_detail.html
{% extends 'base.html' %}


<title>
    {% block title %}
        {{ instance.title }} | {{ block.super }}
    {% endblock title %}
</title>

{% block post_detail_link %}

<li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        {% if instance.image %}
            <img src="{{ instance.image.url }}" class="img-responsive">
        {% endif %}
        <h1>{{ title }} <small>
            {% if instance.draft %}
                <span style="color: red"> (Draft) </span>
            {% endif %}
            {{ instance.publish}}</small></h1>
        {% if instance.user.get_full_name %}
            <p>Author : {{ instance.user.get_full_name }}</p>
        {% endif %}


        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
            Facebook
        </a>

        <a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}">
            Twitter
        </a>

        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}
        /&title={{ instance.title }}summary={{ share_string }}source={{ request.build_absolute_uri }}/">
            Linkedin
        </a>

        <hr>
        {# markdown with javascript or django #}
        {#pip install django-markdown-deux#}
        {#add to INSTALLED_APPS (settings.py) --> markdown_deux#}
        {#for finish add the filter markdown to instance.content  --> {{instance.content | markdown}}#}
        {#Just a note if you use this, place {% load markdown_deux_tags %} into the post_detail.html and not the base,#}
        <div class="row">
            <div class="col-sm-12 ">
                <div class="content-markdown post-detail-item">{{ instance.get_markdown}}</div><br/>

                <hr>

                <div class="fb-like" data-href="{{ request.build_absolute_uri }}"
                     data-layout="button_count" data-action="like"
                     data-size="small" data-show-faces="false" data-share="true">
                </div>

                <div class="fb-comments"
                     data-href="{{ request.build_absolute_uri }}"
                     data-numposts="5">
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

templates/posts_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
    <div class="col-sm-6">
        <h1>Preview</h1>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p  id="preview-content"></p>
    </div>
    </div>
    <div class="col-sm-6 ">
        <h1>Form</h1>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-default" value="Create Post">
        </form>
    </div>
{% endblock content %}

templates/posts_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-sm-6 col-sm-offset-3">
        <h1>{{ title }}</h1>
        <form method="get" action="">
            <div class="input-group">
                <input class="form-control" type="text" name="q" placeholder="search posts" value='{{ request.GET.q }}'><!--"q" is "query" here we can user either-->
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </span>
            </div>
        </form>
        <hr>
        {% for obj in objects_list %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="thumbnail">
                        {% if obj.image %}
                            <img src="{{ obj.image.url }}" class="img-responsive">
                        {% endif %}
                        <div class="caption post-detail-item">
                            {% if obj.draft %}
                                <h3><span style="color: red">Draft</span>(for staff use only)</h3>
                            {% endif %}
                            {% if obj.publish > today %}
                                <h3><span style="color: red">Future Post</span>(for staff use only)</h3>
                            {% endif %}
                            <h3><a href="{{ obj.get_absolute_url}}" >{{ obj.title }}</a>
                                <small>{{ obj.publish}}</small></h3>
                            {% if obj.user.username %}
                                <p>Author: {{ obj.user.username }}</p>
                            {% endif %}
                            {{obj.get_markdown|safe|truncatechars_html:70}}
                            <p><a href="{{ obj.get_absolute_url}}"
                                  class="btn btn-primary" role="button">View</a></p>
                        </div>
                    </div>
                </div>
                </hr>
            </div>
        {% endfor %}
    <div class="pagination">
    <span class="step-links">
        {% if objects_list.has_previous %}
            <a href="?{{page_request_var}}={{ objects_list.previous_page_number }}&q= {{ request.GET.q }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ objects_list.number }} of {{ objects_list.paginator.num_pages }}.
        </span>

        {% if objects_list.has_next %}
            <a href="?{{page_request_var}}={{ objects_list.next_page_number }}&q= {{ request.GET.q }}">next</a>
        {% endif %}
    </span>
</div>


        </div>
{% endblock content %}